[project]
name = "cola"
version = "0.1.0"
description = "A modern asynchronous Python framework inspired by Scrapy."
authors = [{ name = "KingJem", email = "qqqqivy@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["typer", "rich", "ipython","redis","lxml","aioredis","aiohttp","httpx"]

[project.scripts]
cola = "cola.cmdline:app"


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
